name: DEDPIX
favicon: null
layout_spectrum: 0.7457
typography_spectrum: 0.8829195743892342
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4d4d4d'
    - '#a6a6a6'
    - '#797979'
    - '#000000'
  brandStrength: 1
  lightness: 0.4375
  saturation: 0.8125
  rhythmicContrast: 0.7201970608439296
purpose: []
