name: DEDPIX
favicon: null
layout_spectrum: 0
typography_spectrum: 0.8829195743892342
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.8663290024269372
  lightness: 0.44162765541113913
  saturation: 0.8053576992824674
  rhythmicContrast: 0.7201970608439296
purpose: []
